version: 2
jobs:
  build:
    
    working_directory: /home/dellpc/shahul/learning/circleci/sampleapp
    java:
    version: openjdk8

    steps:
      - run: echo '$PATH'
      - checkout

      - restore_cache:
          key: sampleapp-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: sampleapp-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/sampleapp.jar    