machine:
    java:
        version: openjdk8
general:
    artifacts:
        - "target/java-demo.war"
dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

test:
  override:
    - mvn -o surefire:test