machine:
  environment: 
    HOME: /home/dellpc
  java:
    version: openjdk8
general:
  artifacts:
    - "/home/dellpc/shahul/learning/circleci/sampleapp/target/java-demo.jar"
test:
  post:
    - mvn clean install