version: 2
jobs:
  build:
    
    working_directory: ~/javacircleci

    steps:

      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Print the Current HOME PATH
          command: echo $HOME 
      - run:
          name: Print the Current PWD PATH
          command: echo $PWD          
      - run:
          name: Print the Current PWD PATH
          command: echo $PATH                    
      - run: mvn clean install
