version: 2
jobs:
  build:
    
    working_directory: ~/javacircleci

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Print the Current HOME PATH
          command: echo $HOME 
      - run:
          name: Print the Current PWD PATH
          command: echo $PWD          
      - run:
          name: Print the Current PWD PATH
          command: echo $PATH                    
      - restore_cache:
          key: javacircleci-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: javacircleci-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/javacircleci-SNAPSHOT.jar